require('tlm.config.plugin_config.telescope')
require('tlm.config.plugin_config.treesitter')
require('tlm.config.plugin_config.cmp')
require('tlm.config.plugin_config.lsp')
require('tlm.config.plugin_config.project')
